FROM httpd:2.4

EXPOSE 80
EXPOSE 443

COPY ./ssl/* /usr/local/apache2/conf/
# COPY ./ssl/server.key /usr/local/apache2/conf/server.key

RUN sed -i \
        -e 's/^#\(Include .*httpd-ssl.conf\)/\1/' \
        -e 's/^#\(LoadModule .*mod_ssl.so\)/\1/' \
        -e 's/^#\(LoadModule .*mod_socache_shmcb.so\)/\1/' \
        conf/httpd.conf